include parallelDefs

# required files
SORT =  blockRadixSort.h transpose.h quickSort.h
GLOBAL_REQUIRE = parallel.h sequence.h utils.h $(SORT) $(OTHER)
LOCAL_REQUIRE = 
OBJS = suffix.o 

include ../common/timeRequiredFiles
include MakeBench
